services:
  backend:
    image: mysql:8.4.2
    container_name: bookstore-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: bookstore
    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/.docker-volume/bookstore
