services:
  db:
    container_name: bookstore_mysql
    image: mysql:8.0.35
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command:
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    restart: always
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - ~/.volume/bookstore:/var/lib/mysql
